#!/usr/bin/env groovy

/*
  IBM Confidential OCO Source Materials
  (C) Copyright and Licensed by IBM Corp. 2021
  The source code for this program is not published or otherwise
  divested of its trade secrets irrespective of what has
  been deposited with the U.S. Copyright Office.
*/

@Library(['cloud-platform-sre', 'oss-global-library@michelle-jfrog']) _
ciPipeline(
    appName: 'githubzen',
    appSquad: 'api',
    docker: false,
    dependentJobs: [
        '/Pipeline/api-pnp-hooks/master'
    ]
)
