name: Continuity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  #
  # Project checks
  #
  project:
    name: Project Checks
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/continuity
          fetch-depth: 100

      - uses: containerd/project-checks@v1
        with:
          working-directory: src/github.com/containerd/continuity

  tests:
    name: CI Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: [project]

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Setup Go binary path
      shell: bash
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Git line endings
      shell: bash
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/containerd/continuity
        fetch-depth: 25

    - name: Dependencies
      env:
        GO111MODULE: on
      shell: bash
      run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.8

    - name: Lint
      shell: bash
      run: make lint
      working-directory: src/github.com/containerd/continuity

    - name: Build
      shell: bash
      run: make build binaries
      working-directory: src/github.com/containerd/continuity

    - name: Cross-compile
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash
      run: |
          GOOS=freebsd make build binaries
      working-directory: src/github.com/containerd/continuity

    - name: Linux Tests
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        make test
        sudo GOPATH=$GOPATH make root-test
      working-directory: src/github.com/containerd/continuity

    - name: Non-Linux Tests
      if: ${{ !startsWith(matrix.os, 'ubuntu') }}
      shell: bash
      run: make test-compile
      working-directory: src/github.com/containerd/continuity
