# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# \todo Eliminate duplication when/if Dependabot supports YAML anchors

version: 2
updates:
  -
    package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /bridge/opentracing
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /bridge/opencensus
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /bridge/opencensus/test
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/fib
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/prom-collector
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/jaeger
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/namedtracer
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/opencensus
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/otel-collector
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/passthrough
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/prometheus
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /example/zipkin
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/prometheus
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/stdout/stdouttrace
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/stdout/stdoutmetric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/jaeger
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/zipkin
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /sdk
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /internal/metric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /internal/tools
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /metric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /sdk/export/metric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /sdk/metric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /internal/tools/semconv-gen
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/internal/retry
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlptrace
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlptrace/otlptracegrpc
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlptrace/otlptracehttp
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlpmetric
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlpmetric/otlpmetricgrpc
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /trace
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  -
    package-ecosystem: gomod
    directory: /exporters/otlp/otlpmetric/otlpmetrichttp
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly

  -
    package-ecosystem: gomod
    directory: /schema
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
