name: Snyk

on:
  schedule:
    # Run once a day at 9AM PDT (16 UTC) on week days (1-5).
    # Last commit on default branch.
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron:  '0 16 * * 1-5'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          args: --all-projects --exclude=integrations
