image: Visual Studio 2015
environment:
      GOPATH: c:\gopath

stack: go 1.8.7

clone_folder: c:\gopath\src\github.com\docker\docker-credential-helpers
clone_depth: 10

before_build:
  - set PATH=%PATH%;C:\MinGW\bin;

build_script:
  - mingw32-make vet_win wincred

test_script:
  - mingw32-make test

deploy: off

artifacts:
  - path: bin/docker-credential-wincred.exe

configuration: Release
