name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.16', '1.17' ]
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v2
    - run: go mod tidy && git diff --exit-code go.mod go.sum
    - run: go vet ./...
    - run: mv ./tools ./tools.go
    - run: go get github.com/onsi/ginkgo/v2/ginkgo
    - run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --race --trace --fail-on-pending --keep-going
