name: ci-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:

    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13'

    - name: checkout
      run: |
        cd /home/runner/go
        mkdir src/k8s.io -p
        cd /home/runner/go/src/k8s.io
        git clone https://github.com/kubernetes/kube-openapi.git

    - name: build
      run: |
        cd /home/runner/go/src/k8s.io/kube-openapi
        go mod tidy && git diff --exit-code
        go build ./cmd/... ./pkg/...

    - name: test
      run: |
        cd /home/runner/go/src/k8s.io/kube-openapi
        GOPATH=/home/runner/go go test ./cmd/... ./pkg/... ./test/...
