dist: bionic
language: go
go:
    - 1.13.x
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
matrix:
  include:
    - name: "cgroup-v2"
      env:
        - VAGRANT_VERSION=2.2.7
        - FEDORA_VERSION=32
# https://github.com/opencontainers/runc/blob/b207d578ec2d70e20ca6cfa8a32e49ef59dd48dd/.travis.yml#L23-L42
      install:
        - cat /proc/cpuinfo
        - sudo apt-get install -q -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev && wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_$(uname -m).deb && sudo dpkg -i vagrant_${VAGRANT_VERSION}_$(uname -m).deb && rm -f vagrant_${VAGRANT_VERSION}_$(uname -m).deb
        - sudo vagrant plugin install vagrant-libvirt
        - sudo vagrant up && sudo mkdir -p /root/.ssh && sudo sh -c "vagrant ssh-config >> /root/.ssh/config"
      script:
        - sudo ssh default sudo mkdir -p /go/src/github.com/containerd/cgroups
        - ( cd $GOPATH/src/github.com/containerd/cgroups && tar c . ) | sudo ssh default sudo tar Cxv /go/src/github.com/containerd/cgroups
# see https://unix.stackexchange.com/questions/80821/why-does-cd-command-not-work-via-ssh
        - sudo ssh default sudo 'bash -xec "cd /go/src/github.com/containerd/cgroups && pwd && ls -la && GOPATH=/go go test -v ./..."'

install:
    - go get -u github.com/vbatts/git-validation
    - go get -u github.com/kunalkushwaha/ltag

before_script:
    - pushd ..; git clone https://github.com/containerd/project; popd

script:
    - DCO_VERBOSITY=-q ../project/script/validate/dco
    - ../project/script/validate/fileheader ../project/
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
