/*
 * Incident Management
 *
 * The Technical Integration Point (TIP) Incident Management API.  This specification covers the incident management interface.
 *
 * OpenAPI spec version: 0.0.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

// Note: modified package from the generated "TipIncApi" to a more generic one
package datamodel

// ConcernInfo defines the information to create or update an incident based on a concern
type ConcernInfo struct {
	AdjustmentFactor string `json:"adjustment_factor,omitempty"`

	AffectedActivity string `json:"affected_activity,omitempty"`

	AlertId string `json:"alert_id,omitempty"`

	AlertUiUrl string `json:"alert_ui_url,omitempty"`

	AssignedTo string `json:"assigned_to,omitempty"`

	AssignmentGroup string `json:"assignment_group,omitempty"`

	Audience string `json:"audience,omitempty"`

	ClosedBy string `json:"closed_by,omitempty"`

	CloseCode string `json:"close_code,omitempty"`

	CloseNotes string `json:"close_notes,omitempty"`

	Console string `json:"console,omitempty"`

	CorrelationId string `json:"correlation_id,omitempty"`

	Crn ConcernInfoCrn `json:"crn,omitempty"`

	CRNs []string `json:"u_crn,omitempty"`

	CustomerImpacting string `json:"customer_impacting,omitempty"`

	CustomersImpacted string `json:"customers_impacted,omitempty"`

	CustomerImpactDescription string `json:"customer_impact_description,omitempty"`

	DisablePager string `json:"disable_pager,omitempty"`

	Extras []IncidentInfoExtras `json:"extras,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	IncidentId string `json:"incident_id,omitempty"`

	IncidentUiUrl string `json:"incident_ui_url,omitempty"`

	IncidentState string `json:"incident_state,omitempty"`

	IncidentSNState string `json:"incident_snstate,omitempty"`

	IncidentSNStatus string `json:"incident_snstatus,omitempty"`

	Ip string `json:"ip,omitempty"`

	Journal []string `json:"journal,omitempty"`

	MsgType string `json:"tip_msg_type,omitempty"`

	OutageEnd string `json:"outage_end,omitempty"`

	OutageStart string `json:"outage_start,omitempty"`

	PagerURL string `json:"pager_ui_url,omitempty"`

	ProductReadyCompliance string `json:"product_ready_compliance,omitempty"`

	RunbookTOCEnabled string `json:"runbook_toc_enabled,omitempty"`

	RunbookUrl string `json:"runbook_url,omitempty"`

	Severity *int32 `json:"severity,omitempty"`

	ShortDescription string `json:"short_description,omitempty"`

	LongDescription string `json:"long_description,omitempty"`

	Situation string `json:"situation,omitempty"`

	Source string `json:"source,omitempty"`

	Timestamp string `json:"timestamp,omitempty"`

	TotalUnits string `json:"total_units,omitempty"`

	TribeName string `json:"tribe_name,omitempty"`

	UnitType string `json:"unit_type,omitempty"`

	UnitsAffected string `json:"units_affected,omitempty"`

	UserFeedback *string `json:"user_feedback,omitempty"`

	Version string `json:"version,omitempty"`
}

type HrefInfo struct {
	Href string `json:"href,omitempty"`
}
type ConcernQueryResponse struct {
	Offset    int32          `json:"offset"`
	Limit     int32          `json:"limit"`
	Count     int32          `json:"count"`
	First     *HrefInfo      `json:"first,omitempty"`
	Last      *HrefInfo      `json:"last,omitempty"`
	Prev      *HrefInfo      `json:"prev,omitempty"`
	Next      *HrefInfo      `json:"next,omitempty"`
	Resources []*ConcernInfo `json:"resources"`
}
