/*
 * Incident Management
 *
 * The Technical Integration Point (TIP) Incident Management API.  This specification covers the incident management interface.
 *
 * OpenAPI spec version: 0.0.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

// Note: modified package from the generated "TipIncApi" to a more generic one
package datamodel

// REQUIRED. The CRN of the affected service if known.  See format is https&colon;//github.ibm.com/ibmcloud/builders-guide/blob/master/specifications/crn/CRN.md
type PromAnnotations struct {
	AlertId string `json:"TIP_alert_id,omitempty"`

	Version string `json:"TIP_crn_version,omitempty"`

	Cname string `json:"TIP_crn_cname,omitempty"`

	Ctype string `json:"TIP_crn_ctype,omitempty"`

	ServiceName string `json:"TIP_crn_service_name,omitempty"`

	Location string `json:"TIP_crn_location,omitempty"`

	ShortDescription string `json:"TIP_short_description,omitempty"`

	LongDescription string `json:"TIP_long_description,omitempty"`

	ServiceInstance string `json:"TIP_crn_service_instance,omitempty"`

	ResourceType string `json:"TIP_crn_resource_type,omitempty"`

	Resource string `json:"TIP_crn_resource,omitempty"`

	Situation string `json:"TIP_situation,omitempty"`

	Source string `json:"TIP_source,omitempty"`

	Severity int32 `json:"TIP_severity,omitempty"`

	TribeName string `json:"TIP_tribe_name,omitempty"`

	MsgType string `json:"TIP_tip_msg_type,omitempty"`

	TIPVersion string `json:"TIP_version,omitempty"`

	CustomerImpacting string `json:"TIP_customer_impacting,omitempty"`
}
