/*
 * Incident Management
 *
 * The Technical Integration Point (TIP) Incident Management API.  This specification covers the incident management interface.
 *
 * OpenAPI spec version: 0.0.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

// Note: modified package from the generated "TipIncApi" to a more generic one
package datamodel

// REQUIRED. The CRN of the affected service if known.  See format is https&colon;//github.ibm.com/ibmcloud/builders-guide/blob/master/specifications/crn/CRN.md
type ConcernInfoCrn struct {
	Version string `json:"version,omitempty"`

	Cname string `json:"cname,omitempty"`

	Ctype string `json:"ctype,omitempty"`

	ServiceName string `json:"service_name,omitempty"`

	Location string `json:"location,omitempty"`

	Scope string `json:"scope,omitempty"`

	ServiceInstance string `json:"service_instance,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`

	Resource string `json:"resource,omitempty"`
}
