name: Go

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.13, 1.14, 1.15, 1.16]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v --tags=go${{ matrix.go }}

    - name: Coverage
      run: go test -v -cover -race -coverprofile=coverage -covermode=atomic --tags=go${{ matrix.go }}

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage
        verbose: true

  docker-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - alpine
          - archlinux
          - centos
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/run --build --run ${{ matrix.runtime }}

  vagrant-test:
    runs-on: macos-10.15
    strategy:
      matrix:
        runtime:
          - freebsd
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        run: bash ./test/run --build --run ${{ matrix.runtime }}
