version: "{build}"
image: Visual Studio 2017

clone_folder: c:\project

environment:
  PATH: c:\go112\bin;%PATH%
  GOROOT: c:\go112

init:
  - git config --global core.symlinks true

install:
  - go version
  - go env

deploy: false

build_script:
  - appveyor DownloadFile https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_windows_amd64.tar.gz
  - tar -xzf gotestsum_0.3.5_windows_amd64.tar.gz
  - go mod download

test_script:
  - gotestsum
