#!/usr/bin/groovy

// IBM Confidential OCO Source Materials
// (C) Copyright and Licensed by IBM Corp. 2021
//
// The source code for this program is not published or otherwise
// divested of its trade secrets  irrespective of what has
// been deposited with the U.S. Copyright Office.

@Library(['cloud-platform-sre', 'oss-global-library']) _
ciPipeline(
  appName: 'api-pnp-nq2ds',
  appSquad: 'api',
  makeEnvVars: [
    'PG_DB':'pnptest',
    'PG_DB_USER':'pnp',
    'PG_DB_PASS':'pnp',
    'PG_DB_PORT':'5432',
    'PG_DB_IP':'127.0.0.1',
    'NQ_URL':'amqp://guest:guest@127.0.0.1:5672'
  ]
)
