name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit test
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate headers
      run: |
        pushd $(mktemp -d) \
        && go get -u github.com/kunalkushwaha/ltag \
        && popd \
        && ./scripts/validate/fileheader
    - name: Test
      run: go test -v ./...
