name: release-ghcr

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::ghcr.io/${{ github.repository }}:${VERSION}
      - name: docker build
        run: |
          docker build -t ${{ steps.prepare.outputs.ref }} .
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.RELEASE_GHCR_USER_NAME }}
          password: ${{ secrets.RELEASE_GHCR_USER_TOKEN }}
      - name: docker push
        run: |
          docker push ${{ steps.prepare.outputs.ref }}
      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
