/*
 * Incident Management
 *
 * The Technical Integration Point (TIP) Incident Management API.  This specification covers the incident management interface.
 *
 * OpenAPI spec version: 0.0.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pagerdutydatamodel

import (
	"time"
)

// Message is the specific action that PagerDuty is notifying via webhook
type Message struct {
	Type string `json:"type"`
	Data struct {
		Incident struct {
			ID             string    `json:"id"`
			IncidentNumber int       `json:"incident_number"`
			CreatedOn      time.Time `json:"created_on"`
			Status         string    `json:"status"`
			PendingActions []struct {
				Type string    `json:"type"`
				At   time.Time `json:"at"`
			} `json:"pending_actions"`
			HTMLURL     string `json:"html_url"`
			IncidentKey string `json:"incident_key"`
			Service     struct {
				ID          string      `json:"id"`
				Name        string      `json:"name"`
				HTMLURL     string      `json:"html_url"`
				DeletedAt   interface{} `json:"deleted_at"`
				Description string      `json:"description"`
			} `json:"service"`
			EscalationPolicy struct {
				ID        string      `json:"id"`
				Name      string      `json:"name"`
				DeletedAt interface{} `json:"deleted_at"`
			} `json:"escalation_policy"`
			AssignedToUser struct {
				ID      string `json:"id"`
				Name    string `json:"name"`
				Email   string `json:"email"`
				HTMLURL string `json:"html_url"`
			} `json:"assigned_to_user"`
			TriggerSummaryData struct {
				Description string `json:"description"`
				Client      string `json:"client"`
				ClientURL   string `json:"client_url"`
				Subject     string `json:"subject"`
			} `json:"trigger_summary_data"`
			TriggerDetailsHTMLURL string      `json:"trigger_details_html_url"`
			TriggerType           string      `json:"trigger_type"`
			LastStatusChangeOn    time.Time   `json:"last_status_change_on"`
			LastStatusChangeBy    interface{} `json:"last_status_change_by"`
			NumberOfEscalations   int         `json:"number_of_escalations"`
			AssignedTo            []struct {
				At     time.Time `json:"at"`
				Object struct {
					ID      string `json:"id"`
					Name    string `json:"name"`
					Email   string `json:"email"`
					HTMLURL string `json:"html_url"`
					Type    string `json:"type"`
				} `json:"object"`
			} `json:"assigned_to"`
			Urgency string `json:"urgency"`
		} `json:"incident"`
	} `json:"data"`
	ID        string    `json:"id"`
	CreatedOn time.Time `json:"created_on"`
}

// PagerDutyEvents is the struct for the JSON that PagerDuty sends in the webhook
type PagerDutyEvents struct {
	Messages []Message `json:"messages"`
}
