/*
 * Incident Management
 *
 * The Technical Integration Point (TIP) Incident Management API.  This specification covers the incident management interface.
 *
 * OpenAPI spec version: 0.0.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package incidentdatamodel

type ApiInfo struct {

	// The identifier of this client.  This is a unique identifier for the client and must be unique within the API catalog.
	ClientId string `json:"clientId,omitempty"`

	// A brief description of the implementation behind this API.
	Description string `json:"description,omitempty"`

	// A version string of the API in the form of Version.Release.Modification. Example 1.1.0.  If the version property is missing, then version 1.0.0 should be assumed.
	Version string `json:"version,omitempty"`

	// An array of categories fulfilled by this implementation.  In this case 'incidentmgmt'
	Categories []string `json:"categories,omitempty"`

	Concerns *ApiInfoConcerns `json:"concerns,omitempty"`

	Journal *ApiInfoConcerns `json:"journal,omitempty"`

	Healthz *ApiInfoConcerns `json:"healthz,omitempty"`
}
type ExtApiInfo struct {

	// The identifier of this client.  This is a unique identifier for the client and must be unique within the API catalog.
	ClientId string `json:"clientId,omitempty"`

	// A brief description of the implementation behind this API.
	Description string `json:"description,omitempty"`

	// A version string of the API in the form of Version.Release.Modification. Example 1.1.0.  If the version property is missing, then version 1.0.0 should be assumed.
	Version string `json:"version,omitempty"`

	// An array of categories fulfilled by this implementation.  In this case 'incidentmgmt'
	Categories []string `json:"categories,omitempty"`

	Chronology *ApiInfoConcerns `json:"chronology,omitempty"`

	Healthz *ApiInfoConcerns `json:"healthz,omitempty"`

}
