blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/go-agent/blob/master/README.md#support
    about: checkout the README for troubleshooting directions
